node("test") {
    def cicdRepo="git@github.com:doubledna/cicd.git"
    def businessRepo="git@github.com:wujieliyanxia/config.git"
    def mvnCmd="/usr/local/maven/bin/mvn"

    echo "开始构建：config 分支：main Jenkins节点：test"

    stage('拉取cicd代码'){
        git branch: "main", url: "${cicdRepo}"
    }

    stage('拉取业务代码') {
        dir("master") {
            git branch: "main", url: "${businessRepo}"
        }
    }
    
    withEnv(['PATH=/usr/local/maven/bin/:/usr/local/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin']) {
        stage('MVN打包') {
            dir("master") {
                sh "${mvnCmd} clean package -Pdev -Dmaven.test.skip=true -am"
            }
        }
    }

    stage("拷贝jar包") {
        dir("master") {
            sh "ls"
        }
    }
}